#!/usr/bin/env php
<?php
	if($argc == 1) {
		echo "usage: ${argv[0]} MAC-address".PHP_EOL;
		exit(1);
	}

	$mac = $argv[1];

	if(!preg_match("/(?:[A-F0-9]{2}:){5}[A-F0-9]{2}/", $mac)) {
		echo "MAC address '${mac}' is invalid".PHP_EOL;
		exit(1);
	}

	$packet = str_repeat("\xff", 6).str_repeat(pack("H12", str_replace(':', '', $mac)), 16);

	exec("ip r show | grep default", $ip);
	preg_match("/(?:[0-9]{1,3}\.){3}[0-9]{1,3}/", $ip[0], $ip);

	exec("ifconfig | grep ".$ip[0], $addr);
	preg_match("/Bcast:((?:[0-9]{1,3}\.){3}[0-9]{1,3})/", $addr[0], $addr);

	$sock = socket_create(AF_INET, SOCK_DGRAM, SOL_UDP);

	if($sock) {
		$options = socket_set_option($sock, SOL_SOCKET, SO_BROADCAST, true);

		if($options) {
			$send = socket_sendto($sock, $packet, strlen($packet), 0, $addr[1], 9);
			socket_close($sock);
		}
	}
?>
